countries_dict = {
  "Spain": "Spain",
  "Italy": "Italy",
  "France": "France",
  "Germany": "Germany",
  "Turkey": "Turkey",
  "Iran": "Iran",
  "Russia": "Russia",
  "Brazil": "Brazil",
  "Belgium": "Belgium",
  "Canada": "Canada",
  "Netherlands": "Netherlands",
  "Switzerland": "Switzerland",
  "Portugal": "Portugal",
  "India": "India",
  "Peru": "Peru",
  "Sweden": "Sweden",
  "Ireland": "Ireland",
  "Austria": "Austria",
  "Israel": "Israel",
  "Saudi Arabia": "Saudi Arabia",
  "Japan": "Japan",
  "Chile": "Chile",
  "Singapore": "Singapore",
  "Ecuador": "Ecuador",
  "Pakistan": "Pakistan",
  "Mexico": "Mexico",
  "Poland": "Poland",
  "Romania": "Romania",
  "Denmark": "Denmark",
  "Belarus": "Belarus",
  "Indonesia": "Indonesia",
  "Qatar": "Qatar",
  "Norway": "Norway",
  "Ukraine": "Ukraine",
  "Philippines": "Philippines",
  "Australia": "Australia",
  "Malaysia": "Malaysia",
  "Dominican Republic": "Dominican Republic",
  "Panama": "Panama",
  "Colombia": "Colombia",
  "Finland": "Finland",
  "Bangladesh": "Bangladesh",
  "Egypt": "Egypt",
  "Luxembourg": "Luxembourg",
  "South Africa": "South Africa",
  "Morocco": "Morocco",
  "Argentina": "Argentina",
  "Algeria": "Algeria",
  "Thailand": "Thailand",
  "Moldova": "Moldova",
  "Greece": "Greece",
  "Kuwait": "Kuwait",
  "Hungary": "Hungary",
  "Kazakhstan": "Kazakhstan",
  "Bahrain": "Bahrain",
  "Croatia": "Croatia",
  "Iceland": "Iceland",
  "Oman": "Oman",
  "Uzbekistan": "Uzbekistan",
  "Iraq": "Iraq",
  "Estonia": "Estonia",
  "Azerbaijan": "Azerbaijan",
  "Armenia": "Armenia",
  "New Zealand": "New Zealand",
  "Bosnia and Herzegovina": "Bosnia and Herzegovina",
  "Lithuania": "Lithuania",
  "Slovenia": "Slovenia",
  "Slovakia": "Slovakia",
  "Afghanistan": "Afghanistan",
  "Cuba": "Cuba",
  "Cameroon": "Cameroon",
  "Ghana": "Ghana",
  "Bulgaria": "Bulgaria",
  "Djibouti": "Djibouti",
  "Ivory Coast": "Ivory Coast",
  "Tunisia": "Tunisia",
  "Nigeria": "Nigeria",
  "Cyprus": "Cyprus",
  "Latvia": "Latvia",
  "Guinea": "Guinea",
  "Andorra": "Andorra",
  "Lebanon": "Lebanon",
  "Costa Rica": "Costa Rica",
  "Bolivia": "Bolivia",
  "Albania": "Albania",
  "Niger": "Niger",
  "Kyrgyzstan": "Kyrgyzstan",
  "Burkina Faso": "Burkina Faso",
  "Uruguay": "Uruguay",
  "Honduras": "Honduras",
  "San Marino": "San Marino",
  "Palestine": "Palestine",
  "Senegal": "Senegal",
  "Malta": "Malta",
  "Jordan": "Jordan",
  "Taiwan": "Taiwan",
  "Georgia": "Georgia",
  "Guatemala": "Guatemala",
  "Sri Lanka": "Sri Lanka",
  "Kenya": "Kenya",
  "Montenegro": "Montenegro",
  "Isle of Man": "Isle of Man",
  "Venezuela": "Venezuela",
  "Mali": "Mali",
  "Somalia": "Somalia",
  "Vietnam": "Vietnam",
  "Jamaica": "Jamaica",
  "El Salvador": "El Salvador",
  "Paraguay": "Paraguay",
  "Gabon": "Gabon",
  "Sudan": "Sudan",
  "Rwanda": "Rwanda",
  "Brunei": "Brunei",
  "Myanmar": "Myanmar",
  "Cambodia": "Cambodia",
  "Madagascar": "Madagascar",
  "Ethiopia": "Ethiopia",
  "Trinidad and Tobago": "Trinidad and Tobago",
  "Liberia": "Liberia",
  "Aruba": "Aruba",
  "Bermuda": "Bermuda",
  "Monaco": "Monaco",
  "Togo": "Togo",
  "Equatorial Guinea": "Equatorial Guinea",
  "Liechtenstein": "Liechtenstein",
  "Barbados": "Barbados",
  "Zambia": "Zambia",
  "Sint Maarten": "Sint Maarten",
  "Guyana": "Guyana",
  "Cayman Islands": "Cayman Islands",
  "Uganda": "Uganda",
  "Haiti": "Haiti",
  "Sierra Leone": "Sierra Leone",
  "Libya": "Libya",
  "French Polynesia": "French Polynesia",
  "Benin": "Benin",
  "Nepal": "Nepal",
  "Syria": "Syria",
  "Mozambique": "Mozambique",
  "Eritrea": "Eritrea",
  "Saint Martin": "Saint Martin",
  "Mongolia": "Mongolia",
  "Malawi": "Malawi",
  "Chad": "Chad",
  "Zimbabwe": "Zimbabwe",
  "Angola": "Angola",
  "Antigua and Barbuda": "Antigua and Barbuda",
  "Botswana": "Botswana",
  "Laos": "Laos",
  "Belize": "Belize",
  "Fiji": "Fiji",
  "New Caledonia": "New Caledonia",
  "Dominica": "Dominica",
  "Namibia": "Namibia",
  "Grenada": "Grenada",
  "Saint Kitts and Nevis": "Saint Kitts and Nevis",
  "Saint Lucia": "Saint Lucia",
  "Curaçao": "Curaçao",
  "Falkland Islands": "Falkland Islands",
  "Burundi": "Burundi",
  "Greenland": "Greenland",
  "Montserrat": "Montserrat",
  "Nicaragua": "Nicaragua",
  "Gambia": "Gambia",
  "Suriname": "Suriname",
  "Papua New Guinea": "Papua New Guinea",
  "Mauritania": "Mauritania",
  "Bhutan": "Bhutan",
  "Western Sahara": "Western Sahara",
  "British Virgin Islands": "British Virgin Islands",
  "Sao Tome and Principe": "Sao Tome and Principe",
  "South Sudan": "South Sudan",
  "Anguilla": "Anguilla",
  "Yemen": "Yemen",
  "China": "China",
  "USA": "United States of America",
  "UK": "United Kingdom",
  "S. Korea": "South Korea",
  "Czechia": "Czech Republic",
  "UAE": "United Arab Emirates",
  "Serbia": "Republic of Serbia",
  "North Macedonia": "Macedonia",
  "Hong Kong": "Hong Kong S.A.R.",
  "DRC": "Democratic Republic of the Congo",
  "Faeroe Islands": "Faroe Islands",
  "Tanzania": "United Republic of Tanzania",
  "Congo": "Republic of Congo",
  "Cabo Verde": "Cape Verde",
  "Bahamas": "The Bahamas",
  "Guinea-Bissau": "Guinea Bissau",
  "Macao": "Macao S.A.R",
  "Eswatini": "Swaziland",
  "Timor-Leste": "East Timor",
  "CAR": "Central African Republic",
  "St. Vincent Grenadines": "Saint Vincent and the Grenadines",
  "Turks and Caicos": "Turks and Caicos Islands",
  "Vatican City": "Vatican",
  "St. Barth": "Saint Barthelemy",
  "Saint Pierre Miquelon": "Saint Pierre and Miquelon"
}
